AWSTemplateFormatVersion: '2010-09-09'
Description: VPC N. Virginia
Resources:
    MyVPC:
        Type: AWS::EC2::VPC
        Properties:
            CidrBlock: '10.0.0.0/16'
            InstanceTenancy: default
            Tags:
                - Key: Name
                  Value: MyVPC
                - Key: Environment
                  Value: Testing
    MySubnet2c:
        Type: AWS::EC2::Subnet
        Properties:
            AvailabilityZone: us-east-1c
            CidrBlock: '10.0.0.0/24'
            Tags:
                - Key: Name
                  Value: MySubnet2c
            VpcId: !Ref MyVPC
